# -*- coding: utf-8 -*-
"""ML Lab 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1lZfrZ6yEKVHQxtmv9S7Q0f8QNPXkjE
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv("/content/car_price_dataset.csv")

# Select relevant numerical features (excluding 'Price')
X = df.select_dtypes(include=[np.number]).drop(columns=['Price'])

# Scale features for better distance computation
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Data Preprocessing Complete!")
print("Shape of Processed Data:", X_scaled.shape)

# Define Nearest Neighbors model
nn_model = NearestNeighbors(n_neighbors=5, metric='euclidean')  # Find 5 nearest neighbors
nn_model.fit(X_scaled)

print("Nearest Neighbors Model Trained Successfully!")

# Select a random car from the dataset (or specify an index manually)
car_index = 10  # Change this index to test different cars
query_car = X_scaled[car_index].reshape(1, -1)

# Find the 5 nearest neighbors
distances, indices = nn_model.kneighbors(query_car)

# Display recommended similar cars
print(f"\nCar Selected (Index {car_index}):")
print(df.iloc[car_index])

print("\nTop 5 Recommended Cars:")
for idx in indices[0]:
    print(df.iloc[idx])

# Custom car features (Example: [Year, Engine_Size, Mileage, Doors, Owner_Count])
custom_car = np.array([[2020, 2.0, 30000, 4, 1]])

# Scale the input
custom_car_scaled = scaler.transform(custom_car)

# Find the 5 nearest cars
distances, indices = nn_model.kneighbors(custom_car_scaled)

# Display recommendations
print("\nTop 5 Recommended Cars for Custom Input:")
for idx in indices[0]:
    print(df.iloc[idx])







